Add test global fail coverage

diff --git a/.github/workflows/quality.yml b/.github/workflows/quality.yml
--- a/.github/workflows/quality.yml
+++ b/.github/workflows/quality.yml
@@ -28,10 +28,15 @@ jobs:
       uses: alexanderdamiani/pytester-cov@v1.1.0
       with:
         pytest-root-dir: '.'
-        cov-omit-list: 'test/*, temp/main3.py, temp/main4.py'
+        cov-omit-list: 'tests/*'
         cov-threshold-single: 10
-        cov-threshold-total: 10
+        cov-threshold-total: 50
     - name: Commit pytest coverage table
       uses: peter-evans/commit-comment@v1
       with:
         body: ${{ steps.pytest.outputs.output-table }}
+    - name: Coverage total fail - exit
+      if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
+      run: |
+        echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
+        exit 1
