Update Pytester-cov action to 1.1.0 (#30)

diff --git a/.github/workflows/quality.yml b/.github/workflows/quality.yml
--- a/.github/workflows/quality.yml
+++ b/.github/workflows/quality.yml
@@ -18,11 +18,25 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install black pytest pytest-cov
+        pip install black
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
     - name: Lint with black
       run: |
         black --check .
-    - name: Tests with pytest
+    - name: pytest
+      id: pytest
+      uses: alexanderdamiani/pytester-cov@v1.1.0
+      with:
+        pytest-root-dir: '.'
+        cov-omit-list: 'tests/*'
+        cov-threshold-single: 10
+        cov-threshold-total: 50
+    - name: Commit pytest coverage table
+      uses: peter-evans/commit-comment@v1
+      with:
+        body: ${{ steps.pytest.outputs.output-table }}
+    - name: Coverage total fail - exit
+      if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
       run: |
-        pytest --cov-config=.coveragerc --cov-report=xml --cov=. tests
+        echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
+        exit 1
