test coverage pytest action

diff --git a/.github/workflows/quality.yml b/.github/workflows/quality.yml
--- a/.github/workflows/quality.yml
+++ b/.github/workflows/quality.yml
@@ -9,7 +9,9 @@ jobs:
     strategy:
       matrix:
         python-version: [3.8]
-
+    env:
+      COVERAGE_SINGLE: 80
+      COVERAGE_TOTAL: 80
     steps:
     - uses: actions/checkout@v2
     - name: Set up Python ${{ matrix.python-version }}
@@ -27,8 +29,30 @@ jobs:
     - name: Test with pytest
       run: |
         pytest
-    - name: Generate coverage report
-      run : |
-        pytest --cache-clear --cov=ecoindex_cli tests > pytest-coverage.txt
-    - name: Comment coverage
-      uses: coroo/pytest-coverage-commentator@v1.0.2
+    # - name: Generate coverage report
+    #   run : |
+    #     pytest --cache-clear --cov=ecoindex_cli tests > pytest-coverage.txt
+    # - name: Comment coverage
+    #   uses: coroo/pytest-coverage-commentator@v1.0.2
+    - name: pytest
+      id: pytest
+      uses: alexanderdamiani/pytester-cov@v1.0.1
+      with:
+        pytest-root-dir: 'tests'
+        # cov-omit-list: 'test/*, temp/main3.py, temp/main4.py'
+        cov-threshold-single: ${{ env.COVERAGE_TOTAL }}
+        cov-threshold-total: ${{ env.COVERAGE_SINGLE }}
+    - name: Coverage single fail - exit
+      if: ${{ steps.pytest.outputs.cov-threshold-single-fail == 'true' }}
+      run: |
+        echo "cov single fail ${{ steps.pytest.outputs.cov-threshold-single-fail }}"
+        exit 1
+    - name: Coverage total fail - exit
+      if: ${{ steps.pytest.outputs.cov-threshold-total-fail == 'true' }}
+      run: |
+        echo "cov single fail ${{ steps.pytest.outputs.cov-threshold-total-fail }}"
+        exit 1
+    - name: Commit pytest coverage table
+      uses: peter-evans/commit-comment@v1
+      with:
+        body: ${{ steps.pytest.outputs.output-table }}
